# Generated by Django 4.1.7 on 2023-07-14 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("habrieapp", "0003_alter_student_enroll_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicdetail",
            name="session",
            field=models.CharField(default=12, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="enroll_number",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="habrieapp.academicdetail",
            ),
        ),
    ]
