# Generated by Django 4.1.7 on 2023-07-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habrieapp", "0005_remove_document_document_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicdetail",
            name="session",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_name",
            field=models.FileField(null=True, upload_to="document"),
        ),
    ]
